### ISSUE TITLE
网络上传/下载对应功能未正常运行以及关闭显示小鱼后再次显示后出现小鱼信息

### ISSUE THREAD

**Issue by SharkGuo** [Littlefean/cyber-life#1]
1.测试发现有线网下只有在开始运行时会生成一个气泡之后不再生成，且没有网络下载对应的波浪
2.如图所示在关闭“显示小鱼”功能后再次打开会出现默认不显示的小鱼信息
![fish_bug](https://github.com/Littlefean/cyber-life/assets/169376874/1e4949b7-a76c-46f5-bc95-9e99657e8c93)

**Comment by Littlefean** [comment]
感谢反馈，这两个bug我已经修改了，并且在release界面里做了新的发布1.0.1，里面配上了说明。可以看看新的发布是否解决了问题。

之所以一开始会冒一个泡，实际上并不是因为检测到了网络，而只是动画用求余运算的余数大小来控制气泡频率，求余结果0的时候，在第time=0时刻会刚好命中一下。（或许我应该让time从1开始累加，因为一开始冒的那个单独一个的气泡是假的）
